# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Change the below type value to 'html' if you want to develop using static HTML mockups
BROWSERSYNC:
  type: 'wordpress'
  url: 'zf-theme.dev'

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings. UnCSS is not used by default!
UNCSS_OPTIONS:
  html:
    - "_src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "_src/assets/**/*"
    - "!_src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # jQuery-related stuff separately, because in production we use built-in WP version
  jquery:
   - "node_modules/jquery/dist/jquery.js"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "_src/assets/js/app.js"
